### ISSUE TITLE
关于增加md文件

### ISSUE THREAD

**Issue by Yukayo** [senli1073/academic-homepage-template#4]
你好我想问一下，如果我手动增加了几个md文件需要哪些操作能让js读取新的md文件呢

**Comment by Yukayo** [comment]
没事了，解决了，抱歉

**Comment by azureovo** [comment]
> 没事了，解决了，抱歉

hello，请问你是怎么解决的，除了加md文件和index，其他地方还要增加啥吗，为啥我index链接不到我对应的md

**Comment by Yukayo** [comment]
已经忘了，记得我当时把我修改的和他原本的做对比，一步步找不同后来找到了要加个什么东西的地方
